# Generated by Django 6.0.7 on 2026-08-02 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_experience_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='certificate',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='resume',
            name='file',
            field=models.ImageField(upload_to=''),
        ),
    ]
