# Generated by Django 6.0.7 on 2026-08-04 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='certificate',
            field=models.FileField(upload_to='certificates/'),
        ),
    ]
