# Generated by Django 6.0.7 on 2026-08-04 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_alter_experience_certificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='resume',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
